### ISSUE TITLE
Support MPI backend

### ISSUE THREAD

**Issue by streeve** [ORNL/HydraGNN#101]
This is mostly motivated by the use case of running one instance of Hydra per GPU on a node. I was only able to do so with the `mpi` backend and iterating through the `LSB_HOSTS` list.

@jychoi-hpc if there's a better way, please let me know; otherwise, I'll plan to add something like what I describe

**Comment by jychoi-hpc** [comment]
I think if we need to make the following modification in `distributed.py`, it should work:
```
     if dist.is_nccl_available() and torch.cuda.is_available():
         backend = "nccl"
+    elif dist.is_mpi_available():
+        backend = "mpi"
     elif torch.distributed.is_gloo_available():
         backend = "gloo"
     else:
```

We need to figure out what is our priority: ("ncc">"mpi">"gloo") or ("mpi">"NCCL">"gloo")?

Sam, can you try and report here if there is any problem?
