### ISSUE TITLE
ADIOS ImportError is being ignored

### ISSUE THREAD

**Issue by kshitij-v-mehta** [ORNL/HydraGNN#205]
[https://github.com/ORNL/HydraGNN/blob/main/hydragnn/utils/adiosdataset.py#L10C1-L13C9](https://github.com/ORNL/HydraGNN/blob/main/hydragnn/utils/adiosdataset.py#L10C1-L13C9)

An ImportError caused by a missing ADIOS installation is not handled. This leads to errors with the ADIOS datasets further in the code.
[https://github.com/ORNL/HydraGNN/blob/main/hydragnn/utils/adiosdataset.py#L300](https://github.com/ORNL/HydraGNN/blob/main/hydragnn/utils/adiosdataset.py#L300)

`NameError: name 'ad2' is not defined`

**Comment by allaffa** [comment]
@kshitij-v-mehta @jychoi-hpc 
Is this issue still relevant or can we close it?

**Comment by kshitij-v-mehta** [comment]
It is still open. We need to add a clear error message when someone tries to use ADIOS when it is not installed.
