### ISSUE TITLE
Project contribution

### ISSUE THREAD

**Issue by akhilpandey95** [ORNL/HydraGNN#212]
I want to use `HydraGNN` multi-head attention implementation in my research for predicting reproducibility of scholarly articles. I appreciate the contributions of this project in the GNN space. 

I checked `good-first-issue` and found no open issues. I previously commented on #164 for potential contribution. Does this repository support external contribution/collaboration ?

**Comment by allaffa** [comment]
@akhilpandey95  
Thank you for reaching out to us. 
Please send me an email to lupopasinim@ornl.gov and we will coordinate

**Comment by akhilpandey95** [comment]
Thank you, emailed you
