### ISSUE TITLE
AttributeError: module 'adios2' has no attribute 'open'

### ISSUE THREAD

**Issue by jinz2014** [ORNL/HydraGNN#243]
File "/home/HydraGNN/hydragnn/utils/adiosdataset.py", line 330, in __init__
    with ad2.open(self.filename, "r", self.comm) as f:

AttributeError: module 'adios2' has no attribute 'open'

Thanks for your comment

**Comment by allaffa** [comment]
@jinz2014 

The instructions to install and use ADIOS2 are available in the Wiki page of HydraGNN that I updated last week. 
@jychoi-hpc may you confirm that I uploaded all the information needed?

**Comment by jychoi-hpc** [comment]
@jinz2014 it looks like adios2 is not installed. 

as @allaffa mentioned, adios installation info is in the wiki: https://github.com/ORNL/HydraGNN/wiki/Install#ornl-frontier
Especially, try to look step 11-15.

**Comment by jinz2014** [comment]
I installed adios2 (version 2.10) with pip.  https://pypi.org/project/adios2/. Install from source may be required.

Thanks.

**Comment by kshitij-v-mehta** [comment]
Please use ADIOS 2.9.x, as its API has changed in 2.10. You can use pip to install ADIOS if you don't need to follow specific instructions to install it on a system such as Frontier.
