### ISSUE TITLE
tutorial questions

### ISSUE THREAD

**Issue by jinz2014** [ORNL/HydraGNN#246]
Can you please comment where is "within HydraGNN" ?  Is it the json file ?   Can you please describe in details the steps to run an example using the FePt.zip dataset ?

`Set the path to the selected dataset within HydraGNN and run`

Are the ADIOSData file required if users on not on Summit ?

Thanks

**Comment by allaffa** [comment]
The example to run HydraGNN on the FePt.zip dataset is available in `examples/lsms`

The example is also explained in the tutorial available on YouTube (go to time 1:59:05):
https://www.youtube.com/watch?v=U5oHXGcHBdk

I also attach the slides that we used for the tutorial here (FePt examples is at slide 57). 
[LearningOnGraphs2023_HydraGNN.pdf](https://github.com/ORNL/HydraGNN/files/15281377/LearningOnGraphs2023_HydraGNN.pdf)
