### ISSUE TITLE
pickle5 dependency is no longer needed in setup.py

### ISSUE THREAD

**Issue by Lance-Drane** [ORNL/HydraGNN#265]
When following the [Predicting Chemical and Material Molecular Properties With HydraGNN ](https://developer.ornl.gov/predicting-chemical-and-material-molecular-properties-with-hydragnn/) tutorial, there is an instruction to use `pip install -e .`, which will fail if using a Python version >= 3.8 . I was able to fix this on my machine by simply removing the `pickle5` dependency in the `install_requires` list in `setup.py`; the built-in `pickle` module should support all functionality with later Python versions.

**Comment by allaffa** [comment]
@Lance-Drane 
 `pickle5` has been removed from the `install_requires` list in `setup.py` with the #248 that has been merged last month.
