### ISSUE TITLE
Add pre-commit to make contributing easy.

### ISSUE THREAD

**Issue by SauravMaheshkar** [ORNL/HydraGNN#75]
I noticed that in the [`CONTRIBUTING.md`](https://github.com/ORNL/HydraGNN/blob/main/CONTRIBUTING.md) mentions that the contributor must run `black` and `pytest` before contributing. Having [`pre-commit`](https://pre-commit.com/) would make that process much easier and enforce that the developers follow coding conventions.

I'd be more than happy to take this up.

**Comment by streeve** [comment]
That looks like a very nice feature - I agree completely. Support for disabling hooks looks robust enough (I would most likely disable `pytest` until I was ready to create a PR, but want to run `black` for every commit)

Thanks for the interest in our project!
