### ISSUE TITLE
[Feature Request 🚀] Add a `CITATION.cff`

### ISSUE THREAD

**Issue by SauravMaheshkar** [ORNL/HydraGNN#83]
Github recently released a [**new feature**](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) where repository owners can add a `CITATION.cff` file making it easy for others to cite the repository.

Currently the information on the README isn't very helpful as it doesn't provide a `BibTeX` reference. Adding a `CITATION.cff` would make the attribution process very easy.

**Comment by allaffa** [comment]
@SauravMaheshkar 
Thank you. I just created #84
